# Generated by Django 3.1.7 on 2021-02-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='updated_date',
            field=models.DateField(null=True, verbose_name='date updated'),
        ),
    ]
