# Generated by Django 3.1.7 on 2021-03-15 09:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('music', '0003_auto_20210315_2202'), ('music', '0004_auto_20210315_2214'), ('music', '0005_auto_20210315_2215'), ('music', '0006_auto_20210315_2221'), ('music', '0007_auto_20210315_2222'), ('music', '0008_auto_20210315_2222'), ('music', '0009_auto_20210315_2230')]

    dependencies = [
        ('music', '0002_auto_20210228_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('album', models.CharField(max_length=255, null=True)),
                ('artists', models.JSONField(null=True)),
                ('created_date', models.DateField(verbose_name='date created')),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='updated_date',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.AddField(
            model_name='track',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.location'),
        ),
        migrations.AddField(
            model_name='track',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.playlist'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_date',
            field=models.DateField(default=datetime.date(2021, 3, 15), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_date',
            field=models.DateField(default=datetime.date(2021, 3, 15), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='track',
            name='created_date',
            field=models.DateField(default=datetime.date(2021, 3, 15), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_date',
            field=models.DateField(auto_created=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_date',
            field=models.DateField(auto_created=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='track',
            name='created_date',
            field=models.DateField(auto_created=True, verbose_name='date created'),
        ),
        migrations.RemoveField(
            model_name='location',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='location',
            name='updated_date',
            field=models.DateField(null=True, verbose_name='date updated'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='updated_date',
            field=models.DateField(null=True, verbose_name='date updated'),
        ),
    ]
