# Generated by Django 3.1.7 on 2021-04-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210315_2202_squashed_0009_auto_20210315_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='video_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
