# Generated by Django 3.1.7 on 2021-04-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_track_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
